### ISSUE TITLE
release 不能获取 cpu 信息

### ISSUE THREAD

**Issue by hcgrady2** [HiJesse/Magic-Box#1]
红米 10.0 release 包无法获取 cpu 信息，有办法解决吗

**Comment by HiJesse** [comment]
> 红米 10.0 release 包无法获取 cpu 信息，有办法解决吗

@hcgrady2  在高版本的系统里, 系统为了防止release的app跨界获取信息屏蔽了一些命令结果, 例如这里获取cpu信息的top命令.
cpu方面的数据建议在debug环境查看.
